name: retroshare_api_wrapper
description: A Dart package providing a wrapper around the RetroShare JSON-RPC API, enabling interaction with a running RetroShare node from Dart and Flutter applications.
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  http: ^1.3.0
  json_annotation: ^4.9.0

dev_dependencies:  
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  http_parser: ^4.0.2
  json_serializable: ^6.8.0
  test: ^1.25.2


